import {floral,escapeHTML as e} from '../lib.js';
import {guestbookStore} from '../guestbook-store.js';
export function Guestbook(){return `<section class="guestbook narrow-section" id="guestbook"><div class="guestbook-card">${floral('guestbook-flower')}<h2>SỔ LƯU BÚT</h2><form novalidate><label for="guest-name">Tên của bạn</label><input id="guest-name" name="name" maxlength="80" autocomplete="name" placeholder="Tên của bạn" required aria-describedby="guestbook-status"><label for="guest-message">Lời chúc của bạn</label><textarea id="guest-message" name="message" maxlength="1000" placeholder="Gửi đôi lời yêu thương…" required aria-describedby="guestbook-status"></textarea><p id="guestbook-status" class="form-status" role="status" aria-live="polite"></p><div class="submit-row"><button class="primary" type="submit">GỬI LỜI CHÚC</button></div></form></div><div class="guestbook-messages" tabindex="0" role="region" aria-label="Những lời chúc dành cho đôi bạn"></div></section>`;}
export async function mountGuestbook(scroll){const root=document.querySelector('#guestbook'),form=root.querySelector('form'),list=root.querySelector('.guestbook-messages'),status=root.querySelector('.form-status');
 const render=rows=>list.innerHTML=rows.map(row=>`<article class="message"><header><strong>${e(row.name)}</strong><time>${e(new Date(row.date).toLocaleDateString('vi-VN'))}</time></header><p>${e(row.message)}</p></article>`).join('');
 render(await guestbookStore.list());
 root.addEventListener('focusin',()=>scroll.hold('guestbook',true));root.addEventListener('focusout',ev=>{if(!root.contains(ev.relatedTarget)){scroll.hold('guestbook',false);scroll.pauseBriefly();}});root.addEventListener('pointerdown',()=>scroll.pauseBriefly());
 form.addEventListener('submit',async ev=>{ev.preventDefault();const name=form.elements.name,message=form.elements.message;name.removeAttribute('aria-invalid');message.removeAttribute('aria-invalid');if(!name.value.trim()||!message.value.trim()){const field=!name.value.trim()?name:message;status.textContent=field===name?'Vui lòng nhập tên của bạn.':'Vui lòng nhập lời chúc của bạn.';field.setAttribute('aria-invalid','true');field.focus();return;}const button=form.querySelector('button');button.disabled=true;try{await guestbookStore.add({name:name.value,message:message.value});render(await guestbookStore.list());form.reset();status.textContent='Cảm ơn bạn đã gửi lời chúc yêu thương!';list.scrollTop=0;}catch(err){status.textContent=err.message;}finally{button.disabled=false;}});
}
