import {invitationData as d} from '../data.js';
import {floral,image,icon,escapeHTML as e,calendarCells} from '../lib.js';
const title=t=>`<h2>${t}</h2>`;
export function OpeningHero(invitation=d){return `<header class="opening-hero"><p class="eyebrow">SAVE THE DATE</p><div class="envelope-scene" aria-label="Ảnh cưới trong phong bì"><div class="envelope-back"></div><div class="hero-photo">${image(d.hero.src,d.hero.alt,'','eager',d.hero.position)}</div>${floral('hero-flower')}<div class="envelope-front"></div><div class="envelope-seal">${icon('heart')}</div></div><div class="couple-names"><span>${e(invitation.couple.groom)}</span><i>&</i><span>${e(invitation.couple.bride)}</span></div></header>`;}
export function WeddingCeremony(){return `<section class="ceremony section-card burgundy">${floral('card-flower right')}${title('THÔNG TIN LỄ CƯỚI')}<div class="families">${d.families.map(f=>`<div><p class="family-label">${e(f.title)}</p><p>Ông Bà</p><strong>${e(f.father)}<br>${e(f.mother)}</strong><p class="family-address">${e(f.address)}</p></div>`).join('')}</div><p class="formal">TRÂN TRỌNG BÁO TIN<br>LỄ THÀNH HÔN CỦA CHÚNG TÔI</p><h3 class="full-name">${e(d.couple.groomFull)}</h3><p class="birth-order">CHÚ RỂ</p><div class="ampersand">&</div><h3 class="full-name">${e(d.couple.brideFull)}</h3><p class="birth-order">CÔ DÂU</p><p class="formal ceremony-place">LỄ THÀNH HÔN ĐƯỢC CỬ HÀNH TẠI<br><strong>${e(d.event.ceremonyVenue.toUpperCase())}</strong></p><p class="time-row">VÀO LÚC ${e(d.event.ceremonyTime)} <span>${e(d.event.ceremonyWeekday.toUpperCase())}</span></p>${dateBlock(d.event.ceremonyDate)}<p class="lunar">TỨC NGÀY ${e(d.event.ceremonyLunarDate.toUpperCase())} ÂM LỊCH</p></section>`;}
function dateBlock(date){const {year,month,day}=calendarCells(date);return `<div class="date-block"><b>${String(day).padStart(2,'0')}</b><span>THÁNG ${String(month).padStart(2,'0')}<br>${year}</span></div>`;}
export function WeddingCalendar(date=d.event.receptionDate){const c=calendarCells(date);return `<div class="wedding-calendar"><p>Tháng ${c.month} / ${c.year}</p><div class="calendar-grid">${['T2','T3','T4','T5','T6','T7','CN'].map(day=>`<span class="weekday">${day}</span>`).join('')}${c.cells.map(n=>`<span ${n===c.day?'class="wedding-day" aria-label="Ngày cưới '+n+'"':''}>${n||''}</span>`).join('')}</div></div>`;}
export function ReceptionInfo(invitation=d){const event=invitation.event;return `<section class="reception section-card burgundy">${floral('card-flower left')}${title('THÔNG TIN TIỆC CƯỚI')}<h3 class="reception-subtitle">TIỆC CƯỚI SẼ DIỄN RA VÀO LÚC:</h3><p class="time-row">${e(event.receptionWeekday.toUpperCase())}<span>${e(event.receptionTime)}</span></p>${dateBlock(event.receptionDate)}<p class="lunar">TỨC NGÀY ${e(event.receptionLunarDate.toUpperCase())} ÂM LỊCH</p><p class="banquet">KHAI TIỆC<br><strong>${e(event.receptionTime)}</strong></p>${WeddingCalendar(event.receptionDate)}</section>`;}
export function VenueSection(){return '<section class="venue narrow-section"><h2>ĐỊA ĐIỂM HAI GIA ĐÌNH</h2>'+d.families.map(f=>{const q=encodeURIComponent(f.mapQuery || f.address);return `<article class="family-venue"><h3>${e(f.title)}</h3><p>${e(f.address)}</p><iframe title="Bản đồ ${e(f.title)}" src="https://maps.google.com/maps?q=${q}&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a class="outline-button" href="https://www.google.com/maps/search/?api=1&query=${q}" target="_blank" rel="noopener noreferrer">${icon('pin')} Chỉ đường đến ${e(f.title.toLowerCase())}</a></article>`;}).join('')+'</section>';}
export function Footer(invitation=d){return `<footer><div class="ornament">❦</div><p>Sự hiện diện của quý khách là niềm vinh hạnh<br>của gia đình chúng tôi!</p><span>${e(invitation.couple.groom)} & ${e(invitation.couple.bride)}</span></footer>`;}
