name = "wedding-invitation"
main = "src/entry.js"
compatibility_date = "2026-10-01"

[vars]
SITE_URL = "https://datct269.github.io/wedding-invitation/"
LOCAL_SITE_URL = "http://localhost:5173/"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.ttf"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/*.svg"]
fallthrough = true
